import ThemeProvider from "@/context/ThemeProvider/Index";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import QueryClientProvider from "@/context/QueryClientProvider";
import SnakberProvider from "@/context/AppProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prime Wear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <SnakberProvider>
            <QueryClientProvider>{children}</QueryClientProvider>
          </SnakberProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
