import ThemeProvider from "@/context/ThemeProvider/Index";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import QueryClientProvider from "@/context/QueryClientProvider";
import SnakberProvider from "@/context/AppProvider";


const comfortaa = Comfortaa({
  subsets: ["latin"],   // required
  weight: ["400", "700"] // optional: choose weights
});


export const metadata: Metadata = {
  title: "Prime Wear",
  description: "Generated by create next app",
};
 
 export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} antialiased`}>
        <ThemeProvider>
          <SnakberProvider>
            <QueryClientProvider>{children}</QueryClientProvider>
          </SnakberProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
